version: '3.5'

services:
  db:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5434:5432'
    environment:
      POSTGRES_USER: graphql-test
      POSTGRES_DB: graphql-test
      POSTGRES_PASSWORD: graphql-test
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:9999
    environment:
      - DATABASE_URL=postgres://graphql-test:graphql-test@db/graphql-test
      - DEFAULT_FROM_EMAIL=noreply@graphql-test.com
    #  - ELASTICSEARCH_URL=http://search:9200/
    #  - OPENEXCHANGERATES_API_KEY
    #  - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changeme
    volumes:
      - .:/code
    ports:
      - "9999:9999"
    depends_on:
      - db
